sudo: required
services:
    - docker

before_install:
    - docker build -t react-tests -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true react-tests npm run test
    
after_success:
    - docker build -t react-client ./client
    - docker build -t express-server ./express-server
    - docker build -t nginx ./nginx
    - docker build -t worker ./worker
    
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # update the tag to match the docker repo
    - docker tag react-client "$DOCKER_ID"/react-client
    - docker tag express-server "$DOCKER_ID"/express-server
    - docker tag nginx "$DOCKER_ID"/nginx
    - docker tag worker "$DOCKER_ID"/worker
    
    # Take those images and push them to docker hub
    - docker push "$DOCKER_ID"/react-client
    - docker push "$DOCKER_ID"/express-server
    - docker push "$DOCKER_ID"/nginx
    - docker push "$DOCKER_ID"/worker