sudo: required
services:
    - docker

before_install:
    - docker build -t react-tests -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true react-tests npm run test
    
after_success:
    - docker build -t igory/react-client ./client
    - docker build -t igory/express-server ./express-server
    - docker build -t igory/nginx ./nginx
    - docker build -t igory/worker ./worker
    
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Take those images and push them to docker hub
    - docker push igory/react-client
    - docker push igory/express-server
    - docker push igory/nginx
    - docker push igory/worker